# Hugo variables
#
baseurl = "https://isu-graphics.rbind.io/"
languageCode = "en-us"
title = "Graphics Group @ ISU"
theme = "hugo-theme-bootstrap4-blog"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
# optionally override the site's footer with custom copyright text
copyright = "This website lists content related to talks that have either already taken place or scheduled to take place in the Graphics Group. All rights remain with the respective authors."
# copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
#googleAnalytics = "UA-123-45"
#disqusShortname = "XYW"

enableGitInfo = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# After update and auto recommendation, removed the item '_files$' in the 'ignoreFiles' field in config.toml.

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Graphics Group on GitHub"
  url = "https://github.com/isu-graphicsgroup"

[[menu.sidebar]]
  name = "Di's blog: Visiphilia #2"
  url = "http://dicook.org/#posts" #"http://dicook.github.io/blog.html"

[[menu.sidebar]]
  name = "Visiphilia #1"
  url = "http://visiphilia.org/index.html"



# custom navbar menu entry.   See the custom_navbar parameter below for
# details.

[[menu.navbar]]
  name = "Index"
  url = "https://github.com/isu-graphicsgroup/website-repo/blob/master/README.md"


# Theme variables
#
[params]
  # Site author
  author = "Heike Hofmann"

  # Description/subtitle for homepage (can be Markdown)
  description = "We are interested in graphics and computational tools."

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # customise the contents of the navbar at the top of the page.  The default
  # behaviour is to list all static pages not in the posts directory. When the
  # parameter below is set to true you will have to manually add entries to the
  # navbar, either by adding the following menu variable to the front matter of
  # the relevant pages
  #   menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  custom_navbar = true

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  disable_sri = true

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "For the remainder of the Fall 2021 semester, we will meet on Thursdays at 4:00 pm via Zoom. Please join us for presentations on statistical graphics and computational tools. (Contact ganeshk@iastate for access to the Zoom link.) <br> <br> Information about our weekly talks can be found on this website."

    # How many posts to show on the sidebar (Default: 5)
    num_recent_posts = 3

 # [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
 #   twitter = "username"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et
