---
title: Three-dimensional Radial Visualization of High-dimensional Continuous or Discrete Datasets
author: Fan Dai
date: '2019-10-14'
slug: three-dimensional-radial-visualization-of-high-dimensional-continuous-or-discrete-datasets
images:
  - "/post/radial-example.png"
---

We develop methodologies for 3D radial visualization of high-dimensional datasets. Our display engine is called RadViz3D and extends the classic RadViz that visualizes  multivariate data in the 2D plane by mapping every record to a point inside the unit circle. The classic RadViz display has equally-spaced anchor points on the unit circle, with each of them associated with an attribute or feature of the dataset. RadViz3D obtains equi-spaced anchor points exactly for the five Platonic solids and approximately for the other cases via a  Fibonacci grid. We show that distributing anchor points at least approximately uniformly on the 3D unit sphere provides a better visualization %with less effects of ordering than in 2D. We also propose a Max-Ratio Projection (MRP) method that utilizes the group information in high dimensions to provide distinctive lower-dimensional projections that are then displayed using Radviz3D. Our methodology is extended to datasets with discrete and mixed features where a generalized distributional transform is used in conjunction with copula models before applying MRP and RadViz3D visualization.

The slides for the talk can be found [here](https://isu-graphicsgroup.github.io/slide-storage/2019/10-17-Fan-Dai/slides.pdf), and some example code is shown below.

```{r}
library(devtools)
library(rgl)
#install_github("fanne-stat/radviz3d")
library(radviz3d)

data("iris")
features = iris[,-5]
response = as.factor(iris[,5])
radialvis3d(data = features, 
            cl = response,
            domrp = F,
            doGtrans = F, 
            lwd = 2,
            alpha = 0.4, 
            pradius = 0.02, 
            class.labels = levels(response))
rgl::rgl.viewpoint(zoom = 0.6)
rgl::rglwidget()
```

